version: '3.8'

services:
  keycloak:
    image: cefriel/kcong-idp:production
    command: start-dev --import-realm # Re-added --import-realm
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true
      - KC_HTTP2_ENABLED=false
      - KEYCLOAK_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=/keycloak/
      - KC_HOSTNAME_STRICT=false
      - CACHE_STACK=local
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    volumes: # Re-enabled volumes
      - ./deployment/security/keycloak/kcong-bootstrap.json:/opt/keycloak/data/import/kcong-bootstrap.json
      - ./deployment/security/keycloak/teadal-bootstrap.json:/opt/keycloak/data/import/teadal-bootstrap.json
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin

  opa-policy-manager:
    build: .
    ports:
      - "8888:8080" # Exposing on host port 8888, mapping to container port 8080
    environment:
      - MINIO_SERVER=minio:9000
    depends_on:
      - minio
      - postgres 

